# Site settings
title: Stark Inc. Training Site
email: tadej@tano.si
description:
url: "http://start.pyphy.com"
baseurl: ""

# Build settings
production: false
incremental: true
source: src
destination: public
markdown: kramdown
exclude: []

gems:
  - jekyll-assets

assets:
  cache: .asset-cache
  compress:
    css: true
    js: true
  features:
    automatic_img_alt: false
    automatic_img_size: false
  sources:
    - _assets/images
    - _assets/scripts
    - _assets/sass
    - _external/bower_components
